fixes TypeError when using initOnLastDate=true
fixes TypeError data_table.getDistinctValues(...).last is not a function
if widget configured with initOnLastDate=true
possible reason: last() is no longer a valid function (jquery?)